POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email" : "dev2d@gmail.com",
    "famillyName" : "dev", 
    "givenName" : "faiz"
}

###

POST http://localhost:3000/api/companies
Content-Type: application/json

{
    "email" : "feedyourback@gmail.com",
    "companyName" : "saas faizdev"
}

###

GET http://localhost:3000/api/companies?email=feedyourback@gmail.com

###

DELETE http://localhost:3000/api/companies
Content-Type: application/json

{
    "id" : "cm2hkxmfo0002gj73e43p7vb0"
}

###

PATCH  http://localhost:3000/api/companies
Content-Type: application/json

{ "id" : "cm2hmdzkg0003gj73yep94bxx", 
"creatorEmail" : "feedyourback@gmail.com", 
"employeeEmail" : "devops@gmail.com", 
"action" : "DELETE"
}

###

GET http://localhost:3000/api/employees?companyId=cm2hmdzkg0003gj73yep94bxx


###



POST http://localhost:3000/api/rooms
Content-Type: application/json

{
    "action" : "SAVE_DATA",
    "name" : "room1",
    "capacity" : 4 ,
    "description" : "oklm" ,
    "companyId" : "cm2hmdzkg0003gj73yep94bxx"
}

###

POST http://localhost:3000/api/rooms
Content-Type: application/json

{
    "action" : "SAVE_IMAGE",
    "imageUrl" : "image.jpg" ,
    "roomId" : "cm2lzcvl80002sozxn8umzziw"
}

###

GET http://localhost:3000/api/rooms?companyId=cm2hmdzkg0003gj73yep94bxx


###


DELETE http://localhost:3000/api/rooms
Content-Type: application/json

{
 
    "roomId" : "cm2lzwks50007sozxlo8qb2ds"
}


### Créer une réservation
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
  "email": "feedyourback@gmail.com",
  "roomId": "cm2nb43mm0002lbam99vdkbb2",
  "reservationDate": "25/10/2024",  
  "timeSlots": [
    "13:00 - 14:30",
    "22:00 - 22:30"
  ]
}

### Afficher les disponibilitées
POST http://localhost:3000/api/disponibilities
                               disponibilities

{
    "roomId": "cm2nb43mm0002lbam99vdkbb2",
    "reservationDate": "25/10/2024"
}


### Récuperre les reservations dune personne

GET http://localhost:3000/api/reservations?email=feedyourback@gmail.com 



### supprimer une reservation

DELETE http://localhost:3000/api/reservations
Content-Type: application/json

{
  "id": "cm2oknnb8000h6y21qnzrlt9m"
}

###

DELETE http://localhost:3000/api/cleanupReservations

